version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: 9900proj
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: .
    image: lumos_backend
    ports:
      - "8080:8080"
    environment:
#      docker环境（不能用localhost）
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/9900proj
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db

volumes:
  mysql_data: